// <auto-generated />
using Admin5.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Coding_challenge_BE.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Coding_challenge_BE.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Password")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "soufian.chaoui@gmail.com",
                            FirstName = "soufiane",
                            LastName = "chaoui",
                            Password = "123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "soufian.chaoui2@gmail.com",
                            FirstName = "soufiane2",
                            LastName = "chaoui2",
                            Password = "123"
                        },
                        new
                        {
                            Id = 3,
                            Email = "soufian.chaoui3@gmail.com",
                            FirstName = "soufiane3",
                            LastName = "chaoui3",
                            Password = "123"
                        },
                        new
                        {
                            Id = 4,
                            Email = "soufian.chaoui4@gmail.com",
                            FirstName = "soufiane4",
                            LastName = "chaoui4",
                            Password = "123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
